apiVersion: opensearch.aws.upbound.io/v1beta1
kind: Domain
metadata:
  name: test-opensearch-domain
spec:
  forProvider:
    region: us-east-2
    domainName: test-opensearch-domain
    engineVersion: "OpenSearch_2.11"
  initProvider:
    clusterConfig:
      - instanceType: t3.small.search
        instanceCount: 1
    ebsOptions:
      - ebsEnabled: true
        volumeSize: 10
        volumeType: gp3
  providerConfigRef:
    name: default
