apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-opensearchserverless-irsa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    chart: raw
    repoURL: https://bedag.github.io/helm-charts
    targetRevision: 2.0.0
    helm:
      valuesObject:
        resources:
          # IAM Policy for Crossplane OpenSearch Serverless Provider
          - apiVersion: iam.aws.upbound.io/v1beta1
            kind: Policy
            metadata:
              name: crossplane-opensearchserverless-policy
              annotations:
                crossplane.io/external-name: fargate-eks-cluster-crossplane-opensearchserverless-policy
            spec:
              forProvider:
                description: IAM policy for Crossplane OpenSearch Serverless provider
                policy: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Effect": "Allow",
                        "Action": [
                          "aoss:*"
                        ],
                        "Resource": "*"
                      }
                    ]
                  }
              providerConfigRef:
                name: default

          # IAM Role for Crossplane OpenSearch Serverless Provider (using IRSA)
          - apiVersion: iam.aws.upbound.io/v1beta1
            kind: Role
            metadata:
              name: crossplane-opensearchserverless-role
              annotations:
                crossplane.io/external-name: fargate-eks-cluster-crossplane-opensearchserverless-role
            spec:
              forProvider:
                assumeRolePolicy: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Effect": "Allow",
                        "Principal": {
                          "Federated": "arn:aws:iam::941497602196:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/789C3219F52C84D9EBE9A9A29310CCA7"
                        },
                        "Action": "sts:AssumeRoleWithWebIdentity",
                        "Condition": {
                          "StringLike": {
                            "oidc.eks.us-east-2.amazonaws.com/id/789C3219F52C84D9EBE9A9A29310CCA7:sub": "system:serviceaccount:crossplane-system:provider-aws-opensearchserverless-*"
                          },
                          "StringEquals": {
                            "oidc.eks.us-east-2.amazonaws.com/id/789C3219F52C84D9EBE9A9A29310CCA7:aud": "sts.amazonaws.com"
                          }
                        }
                      }
                    ]
                  }
              providerConfigRef:
                name: default

          # Attach policy to OpenSearch Serverless role
          - apiVersion: iam.aws.upbound.io/v1beta1
            kind: RolePolicyAttachment
            metadata:
              name: crossplane-opensearchserverless-attachment
            spec:
              forProvider:
                policyArnRef:
                  name: crossplane-opensearchserverless-policy
                roleRef:
                  name: crossplane-opensearchserverless-role
              providerConfigRef:
                name: default

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: iam.aws.upbound.io
      kind: Policy
      jsonPointers:
        - /status
    - group: iam.aws.upbound.io
      kind: Role
      jsonPointers:
        - /status
    - group: iam.aws.upbound.io
      kind: RolePolicyAttachment
      jsonPointers:
        - /status
