apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-opensearch-providers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    chart: raw
    repoURL: https://bedag.github.io/helm-charts
    targetRevision: 2.0.0
    helm:
      valuesObject:
        resources:
          - apiVersion: pkg.crossplane.io/v1beta1
            kind: DeploymentRuntimeConfig
            metadata:
              name: provider-aws-opensearch-config
            spec:
              serviceAccountTemplate:
                metadata:
                  annotations:
                    eks.amazonaws.com/role-arn: arn:aws:iam::941497602196:role/fargate-eks-cluster-crossplane-opensearch-role
              deploymentTemplate:
                spec:
                  selector:
                    matchLabels:
                      pkg.crossplane.io/provider: provider-aws-opensearch
                  template:
                    spec:
                      containers:
                        - name: package-runtime
                          resources:
                            limits:
                              cpu: 500m
                              memory: 1Gi
                            requests:
                              cpu: 100m
                              memory: 512Mi
          - apiVersion: pkg.crossplane.io/v1
            kind: Provider
            metadata:
              name: provider-aws-opensearch
            spec:
              package: xpkg.upbound.io/upbound/provider-aws-opensearch:v1.16.0
              runtimeConfigRef:
                name: provider-aws-opensearch-config
              revisionActivationPolicy: Automatic
              revisionHistoryLimit: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: pkg.crossplane.io
      kind: Provider
      jsonPointers:
        - /status
