apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-console-access
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    chart: raw
    repoURL: https://bedag.github.io/helm-charts
    targetRevision: 2.0.0
    helm:
      valuesObject:
        resources:
          # aws-auth ConfigMap for EKS authentication
          # Maps IAM roles to Kubernetes RBAC groups
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: aws-auth
              namespace: kube-system
            data:
              mapRoles: |
                - rolearn: arn:aws:iam::941497602196:role/fargate-eks-cluster-fargate-pod-execution-role
                  username: system:node:{{SessionName}}
                  groups:
                    - system:bootstrappers
                    - system:nodes
                    - system:node-proxier
                - rolearn: arn:aws:iam::941497602196:role/SAML-ACCT-OWNER
                  username: console-admin
                  groups:
                    - console-viewers

          # ClusterRoleBinding for console viewers
          # Grants cluster-admin access to the console-viewers group
          # Change to 'view' ClusterRole if you only want read-only access
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: console-viewers-binding
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: cluster-admin  # Use 'view' for read-only, 'edit' for read-write without cluster-wide changes
            subjects:
              - kind: Group
                name: console-viewers
                apiGroup: rbac.authorization.k8s.io

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
