apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    chart: temporal
    repoURL: https://go.temporal.io/helm-charts
    targetRevision: 0.70.0
    helm:
      releaseName: temporaltest
      valuesObject:
        server:
          replicaCount: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi

          # Service account with IRSA annotation
          serviceAccount:
            create: true
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::941497602196:role/temporal-datastore-role"

          config:
            persistence:
              default:
                driver: "cassandra"
                cassandra:
                  hosts: "cassandra.us-east-2.amazonaws.com"
                  port: 9142
                  keyspace: "temporal"
                  user: ""
                  password: ""
                  tls:
                    enabled: true
                    certFile: ""
                    keyFile: ""
                    caFile: ""
                    enableHostVerification: true
              visibility:
                driver: "cassandra"
                cassandra:
                  hosts: "cassandra.us-east-2.amazonaws.com"
                  port: 9142
                  keyspace: "temporal_visibility"
                  user: ""
                  password: ""
                  tls:
                    enabled: true
                    certFile: ""
                    keyFile: ""
                    caFile: ""
                    enableHostVerification: true

        # Disable internal Cassandra
        cassandra:
          enabled: false

        # Enable OpenSearch for visibility (using external OpenSearch Serverless)
        elasticsearch:
          enabled: false

        # We'll use OpenSearch Serverless via custom config
        # opensearch:
        #   url: "https://temporal-visibility-xxxxx.us-east-2.aoss.amazonaws.com"
        #   version: "v7"

        prometheus:
          enabled: false

        grafana:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: temporal

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
