apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.fairwinds.com/stable
    chart: vpa
    targetRevision: 4.5.0
    helm:
      values: |
        # VPA configuration for Fargate
        recommender:
          enabled: true
        updater:
          enabled: false  # Don't auto-update pods, just recommend
        admissionController:
          enabled: false  # Don't auto-apply on pod creation
  destination:
    server: https://kubernetes.default.svc
    namespace: vpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
